const words = [
  // PERSONAL INFORMATION
  { en: "address", pl: "adres" },
  { en: "email", pl: "adres e-mail" },
  { en: "postal address", pl: "adres pocztowy" },
  { en: "age", pl: "wiek" },
  { en: "birth", pl: "narodziny" },
  { en: "date of birth", pl: "data urodzenia" },
  { en: "place of birth", pl: "miejsce urodzenia" },
  { en: "citizen", pl: "obywatel, obywatelka" },
  { en: "divorced", pl: "rozwiedziony" },
  { en: "family name", pl: "nazwisko" },
  { en: "female", pl: "kobieta; żeński" },
  { en: "first name", pl: "imię" },
  { en: "ID", pl: "dokument tożsamości" },
  { en: "ID number", pl: "numer dokumentu tożsamości" },
  { en: "male", pl: "mężczyzna; męski" },
  { en: "marital status", pl: "stan cywilny" },
  { en: "married", pl: "żonaty, zamężna" },
  { en: "mobile phone number", pl: "numer telefonu komórkowego" },
  { en: "nationality", pl: "narodowość" },
  { en: "occupation", pl: "zawód" },
  { en: "passport number", pl: "numer paszportu" },
  { en: "sex", pl: "płeć" },
  { en: "single", pl: "stanu wolnego" },
  { en: "surname", pl: "nazwisko" },
  { en: "widow", pl: "wdowa" },
  { en: "widower", pl: "wdowiec" },

  // STAGES OF LIFE
  { en: "adolescent", pl: "osoba w wieku dojrzewania" },
  { en: "adult", pl: "dorosły; osoba dorosła" },
  { en: "at the age of", pl: "w wieku" },
  { en: "baby", pl: "dziecko, niemowlę" },
  { en: "child", pl: "dziecko" },
  { en: "childhood", pl: "dzieciństwo" },
  { en: "dead", pl: "martwy" },
  { en: "death", pl: "śmierć" },
  { en: "elderly", pl: "w starszym wieku" },
  { en: "generation", pl: "pokolenie" },
  { en: "grow older", pl: "starzeć się" },
  { en: "grow up", pl: "dorastać" },
  { en: "grown-up", pl: "dorosły; osoba dorosła" },
  { en: "in his/her early twenties", pl: "po dwudziestce" },
  { en: "in his/her late thirties", pl: "przed czterdziestką" },
  { en: "in his/her mid-fifties", pl: "w wieku około pięćdziesięciu pięciu lat" },
  { en: "infant", pl: "niemowlę, małe dziecko" },
  { en: "kid", pl: "dzieciak" },
  { en: "middle age", pl: "wiek średni" },
  { en: "middle-aged", pl: "w średnim wieku" },
  { en: "old age", pl: "starość" },
  { en: "over twenty", pl: "po dwudziestce" },
  { en: "teenager", pl: "nastolatek, nastolatka" },
  { en: "young", pl: "młody" },
  { en: "youth", pl: "młodość" },
 

  // APPEARANCE
  { en: "attractive", pl: "atrakcyjny" },
  { en: "beautiful", pl: "piękny" },
  { en: "good-looking", pl: "przystojny, atrakcyjny" },
  { en: "plain", pl: "przeciętny" },
  { en: "pretty", pl: "ładny" },

  // HEIGHT
  { en: "of medium height", pl: "średniego wzrostu" },
  { en: "short", pl: "niski" },
  { en: "tall", pl: "wysoki" },

  // BUILD
  { en: "athletic build", pl: "sportowa sylwetka" },
  { en: "broad shoulders", pl: "szerokie ramiona" },
  { en: "overweight", pl: "z nadwagą" },
  { en: "plump", pl: "puszysty" },
  { en: "skinny", pl: "bardzo chudy" },
  { en: "slim", pl: "szczupły" },
  { en: "thin", pl: "chudy" },
  { en: "well-built", pl: "dobrze zbudowany" },

  // FACE
  { en: "beard", pl: "broda" },
  { en: "cheek", pl: "policzek" },
  { en: "pale/pink cheeks", pl: "blade/różowe policzki" },
  { en: "chin", pl: "podbródek" },
  { en: "complexion", pl: "cera" },
  { en: "dark/pale/rosy/tanned complexion", pl: "ciemna/blada/rumiana/opalona cera" },
  { en: "dark circles under your eyes", pl: "cienie pod oczami, podkrążone oczy" },
  { en: "eyebrow", pl: "brew" },
  { en: "eyelash", pl: "rzęsa" },
  { en: "forehead", pl: "czoło" },
  { en: "freckles", pl: "piegi" },
  { en: "lip", pl: "warga" },
  { en: "full lips", pl: "pełne usta" },
  { en: "lovely smile", pl: "uroczy uśmiech" },
  { en: "moustache", pl: "wąsy" },
  { en: "mouth", pl: "usta" },
  { en: "tongue", pl: "język" },
  { en: "tooth", pl: "ząb" },
  { en: "teeth", pl: "zęby" },
  { en: "wrinkles", pl: "zmarszczki" },

  // HAIR
  { en: "bald", pl: "łysy" },
  { en: "curly", pl: "kręcone" },
  { en: "dyed", pl: "farbowane" },
  { en: "fair", pl: "jasne" },
  { en: "fringe", pl: "grzywka" },
  { en: "go bald", pl: "łysieć" },
  { en: "grey", pl: "siwe" },
  { en: "ponytail", pl: "kucyk" },
  { en: "short", pl: "krótkie" },
  { en: "shoulder-length", pl: "do ramion" },
  { en: "spiky", pl: "nastroszone, sterczące" },
  { en: "straight", pl: "proste" },
  { en: "wavy", pl: "faliste" },
  { en: "white", pl: "siwe" },

  // OTHER WORDS AND COLLOCATIONS
  { en: "look", pl: "wygląd" },
  { en: "looks", pl: "wygląd" },
  { en: "put on weight", pl: "przybierać na wadze" },
  { en: "tattoo", pl: "tatuaż" },

  // CLOTHES
  { en: "blouse", pl: "bluzka" },
  { en: "bra", pl: "stanik" },
  { en: "button", pl: "guzik" },
  { en: "coat", pl: "płaszcz" },
  { en: "dress", pl: "sukienka" },
  { en: "dress code", pl: "zasady dotyczące ubioru" },
  { en: "fleece", pl: "polar" },
  { en: "hood", pl: "kaptur" },
  { en: "jacket", pl: "marynarka, żakiet, kurtka" },
  { en: "jeans", pl: "dżinsy" },
  { en: "jumper", pl: "sweter" },
  { en: "label", pl: "metka" },
  { en: "outfit", pl: "strój" },
  { en: "pocket", pl: "kieszeń" },
  { en: "pyjamas", pl: "piżama" },
  { en: "shirt", pl: "koszula" },
  { en: "skirt", pl: "spódnica" },
  { en: "sleeve", pl: "rękaw" },
  { en: "sock", pl: "skarpetka" },
  { en: "suit", pl: "garnitur" },
  { en: "sweater", pl: "sweter" },
  { en: "sweatshirt", pl: "bluza" },
  { en: "tie", pl: "krawat" },
  { en: "tights", pl: "rajstopy" },
  { en: "tracksuit", pl: "dres" },
  { en: "tracksuit bottoms", pl: "spodnie od dresu" },
  { en: "trousers", pl: "spodnie" },
  { en: "underpants", pl: "slipy" },
  { en: "underwear", pl: "bielizna" },
  { en: "uniform", pl: "mundur" },
  { en: "school uniform", pl: "mundurek szkolny" },
  { en: "zip", pl: "zamek błyskawiczny" },
  

  // SHOES AND ACCESSORIES
  { en: "baseball cap", pl: "czapka z daszkiem" },
  { en: "belt", pl: "pasek" },
  { en: "boots", pl: "kozaki, wysokie buty" },
  { en: "snow boots", pl: "śniegowce" },
  { en: "bracelet", pl: "bransoletka" },
  { en: "briefcase", pl: "teczka, aktówka" },
  { en: "earrings", pl: "kolczyki" },
  { en: "flat shoes", pl: "buty na płaskim obcasie" },
  { en: "glasses", pl: "okulary" },
  { en: "gloves", pl: "rękawiczki" },
  { en: "handbag", pl: "torebka" },
  { en: "hat", pl: "kapelusz, czapka" },
  { en: "high heels", pl: "buty na wysokim obcasie" },
  { en: "jewellery", pl: "biżuteria" },
  { en: "necklace", pl: "naszyjnik" },
  { en: "piercing", pl: "piercing, kolczyk" },
  { en: "sandals", pl: "sandały" },
  { en: "scarf", pl: "szalik, apaszka" },
  { en: "sunglasses", pl: "okulary przeciwsłoneczne" },
  { en: "prescription sunglasses", pl: "korygujące okulary przeciwsłoneczne" },
  { en: "trainers", pl: "buty sportowe" },

  // ADJECTIVES
  { en: "casual", pl: "nieformalny, codzienny" },
  { en: "checked", pl: "w kratę" },
  { en: "comfortable/uncomfortable", pl: "wygodny/niewygodny" },
  { en: "cotton", pl: "bawełniany" },
  { en: "denim", pl: "dżinsowy" },
  { en: "designer", pl: "designerski, markowy" },
  { en: "elegant", pl: "elegancki" },
  { en: "fashionable/unfashionable", pl: "modny/niemodny" },
  { en: "floral", pl: "kwiecisty" },
  { en: "formal/informal", pl: "formalny/nieformalny" },
  { en: "good quality", pl: "dobrej jakości" },
  { en: "in good condition", pl: "w dobrym stanie" },
  { en: "khaki", pl: "w kolorze khaki" },
  { en: "leather", pl: "skórzany" },
  { en: "loose", pl: "luźny" },
  { en: "old-fashioned", pl: "niemodny, staromodny" },
  { en: "patterned", pl: "wzorzysty" },
  { en: "poor quality", pl: "złej jakości" },
  { en: "second-hand", pl: "używany" },
  { en: "smart", pl: "elegancki" },
  { en: "silk", pl: "jedwabny" },
  { en: "straight leg", pl: "o prostej nogawce" },
  { en: "stunning", pl: "olśniewający" },
  { en: "tight", pl: "obcisły" },
  { en: "trendy", pl: "modny" },
  { en: "ugly", pl: "brzydki" },
  { en: "warm", pl: "ciepły" },

  // VERBS AND PHRASES
  { en: "dress", pl: "ubierać (się)" },
  { en: "dress up as somebody/something", pl: "przebrać się za kogoś/coś" },
  { en: "fit", pl: "pasować pod względem rozmiaru" },
  { en: "get a haircut", pl: "ostrzyc się" },
  { en: "get changed", pl: "przebrać się" },
  { en: "get dressed", pl: "ubrać się" },
  { en: "iron a shirt", pl: "wyprasować koszulę" },
  { en: "match", pl: "pasować pod względem koloru, wzoru" },
  { en: "polish shoes", pl: "wypastować buty" },
  { en: "put on", pl: "zakładać ubranie" },
  { en: "put on make-up", pl: "nakładać makijaż" },
  { en: "suit", pl: "pasować do osoby, jej stylu" },
  { en: "take off", pl: "zdjąć z siebie ubranie" },
  { en: "try on", pl: "przymierzyć" },
  { en: "wear", pl: "nosić, mieć na sobie" }
];
